In [1]:
import pandas as pd
import numpy as np
import os
import torch
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import log_loss
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Put the directory of the datasets here
os.chdir(r"/content/drive/My Drive/STA-ML")

path = os.getcwd()
print(path)

/content/drive/My Drive/STA-ML


In [4]:
# Load data into DataFrame
train_data = np.loadtxt(path+'/HW12/X.dat')
test_data =  np.loadtxt(path+'/HW12/Xtest.dat')
train_labels =  np.loadtxt(path+'/HW12/Y.dat')
test_labels =  np.loadtxt(path+'/HW12/Ytest.dat')
# Add a foward column  of 1's on training datafor the linear constant

#data.insert(0,'const',1)

print(train_data)
print(train_labels)

[[ 92. 115. 120. ... 107. 113.  87.]
 [ 84. 102. 106. ...  99. 104.  79.]
 [ 84. 102. 102. ...  99. 104.  79.]
 ...
 [ 68.  75. 108. ... 100. 104.  85.]
 [ 71.  87. 108. ...  91. 104.  85.]
 [ 71.  91. 100. ...  91. 100.  81.]]
[2. 2. 2. ... 3. 3. 3.]


In [5]:
train_data.shape

(4435, 36)

In [6]:
train_labels.shape

(4435,)

In [7]:
print(max(train_labels),min(train_labels))

5.0 0.0


In [8]:
ss=StandardScaler()
ss.fit(train_data)
tf_X_train=ss.transform(train_data)
tf_X_test=ss.transform(test_data)

In [9]:
max(train_labels)

5.0

In [10]:
tf_X_train = torch.tensor(tf_X_train,dtype=torch.double, requires_grad=True)

train_labels = torch.tensor(train_labels,dtype=torch.double, requires_grad=True)

In [40]:
#There are 6 class labels
#Must implement FSA function with Vapnik Loss (L = sum(u_y - u_k) w/ u = np.dot(X.T,W))

theta = torch.zeros((train_data.shape[1],6), dtype=torch.double)   # Initialize to 36 x 6 matrix
cost = []
lamb = 0.1
eta = 0.01
m  = train_data.shape[0]
p = train_data.shape[1]
mu = 30
k = 30
Niter = 300
for i in range(1,Niter):
  z = torch.matmul(tf_X_train,theta)
  A = (1/(1+(torch.exp(-z))))
  pred = A.argmax(dim=1)
  diff = (pred - train_labels)
  temp = torch.log(1+torch.exp(diff)).sum() + (lamb/(m)) * theta.square_().sum()
  cost.append(temp.detach().numpy())
  temp = temp.clone().detach().requires_grad_(True)
  temp.backward()
  theta = theta - (eta * temp.grad) - (eta * (lamb) * theta)
  temp2 = (Niter-(2*i))/((2*i*mu)+Niter)
  mi = int(k + ((p-k)*max(0,temp2)))
  if mi > k :
    sorted = np.sort(theta.detach().numpy(),axis=0)
    reverse_sorted = np.flip(sorted, axis=None)
    temp1 = reverse_sorted[0:mi,0]
    for j,lol in enumerate(theta):
      if lol in temp1:
        pass
      else:
        theta[j,0]=0
  

In [16]:
theta = torch.zeros((train_data.shape[1],6), dtype=torch.double, requires_grad=True)   # Initialize to 36 x 6 matrix
cost = []
tf_X_train = torch.tensor(tf_X_train,dtype=torch.double, requires_grad=True)

train_labels = torch.tensor(train_labels,dtype=torch.double, requires_grad=True)

z = torch.matmul(tf_X_train,theta)
A = (1/(1+(torch.exp(-z))))
pred = A.argmax(dim=1)
diff = (pred - train_labels)
temp = torch.log(1+torch.exp(diff)).sum()
#cost.append(temp.numpy())
temp = torch.tensor(temp,requires_grad=True)
temp.backward()
theta = theta - eta* temp.grad

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  del sys.path[0]


In [41]:
cost

[array(1050.74869325),
 array(1451.17439546),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1451.17439545),
 array(1734.80361389),
 array(1451.17439553),
 array(1734.80361389),
 array(1451.17439553),
 array(1734.80361389),
 array(1451.17439553),
 array(1733.34538774),
 array(1416.12462109),
 array(1130.33276103),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050.74869373),
 array(1050

In [34]:
print(torch.autograd.backward(grad_tensor))

None


array([[2., 2., 2., ..., 3., 3., 3.],
       [2., 2., 2., ..., 3., 3., 3.],
       [2., 2., 2., ..., 3., 3., 3.],
       ...,
       [2., 2., 2., ..., 3., 3., 3.],
       [2., 2., 2., ..., 3., 3., 3.],
       [2., 2., 2., ..., 3., 3., 3.]])

In [ ]:
cost[1].shape

(4435,)

In [ ]:
import sklearn as skl

In [ ]:
skl.utils.all_estimators

<function sklearn.utils.all_estimators>